### ISSUE TITLE
A gated shift register module

### ISSUE THREAD

**Issue by qian-gu** [pulp-platform/common_cells#169]
I have developed a new version of `shift_reg` which has a valid flag for data to enable DC insert ICG for the internal datapath, the new version shift_reg is backward compatible with the older one and has a better power comuption. Is it welcomed to add it to this library?

**Comment by niwis** [comment]
Hi @qian-gu, contributions are always welcome! Feel free to open a PR with your changes so that we can discuss them concretely.

**Comment by qian-gu** [comment]
The new PR #170  has been open.
